/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AnalyzeResult
} from '../models/analyzeResult';

import type {
  Widget
} from '../models/widget';

import type {
  WidgetList
} from '../models/widgetList';


export const getWidgetsListResponseMock = (overrideResponse: Partial<Extract<WidgetList, object>> = {}): WidgetList => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.alpha({length: {min: 10, max: 20}}), weight: faker.number.int(), color: faker.helpers.arrayElement(['red','blue'] as const)})), ...overrideResponse})

export const getWidgetsCreateResponseMock = (overrideResponse: Partial<Extract<Widget, object>> = {}): Widget => ({id: faker.string.alpha({length: {min: 10, max: 20}}), weight: faker.number.int(), color: faker.helpers.arrayElement(['red','blue'] as const), ...overrideResponse})

export const getWidgetsReadResponseMock = (overrideResponse: Partial<Extract<Widget, object>> = {}): Widget => ({id: faker.string.alpha({length: {min: 10, max: 20}}), weight: faker.number.int(), color: faker.helpers.arrayElement(['red','blue'] as const), ...overrideResponse})

export const getWidgetsUpdateResponseMock = (overrideResponse: Partial<Extract<Widget, object>> = {}): Widget => ({id: faker.string.alpha({length: {min: 10, max: 20}}), weight: faker.number.int(), color: faker.helpers.arrayElement(['red','blue'] as const), ...overrideResponse})

export const getWidgetsAnalyzeResponseMock = (overrideResponse: Partial<Extract<AnalyzeResult, object>> = {}): AnalyzeResult => ({id: faker.string.alpha({length: {min: 10, max: 20}}), analysis: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getWidgetsListMockHandler = (overrideResponse?: WidgetList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WidgetList> | WidgetList), options?: RequestHandlerOptions) => {
  return http.get('*/widgets', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getWidgetsListResponseMock(),
      { status: 200
      })
  }, options)
}

export const getWidgetsCreateMockHandler = (overrideResponse?: Widget | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Widget> | Widget), options?: RequestHandlerOptions) => {
  return http.post('*/widgets', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getWidgetsCreateResponseMock(),
      { status: 200
      })
  }, options)
}

export const getWidgetsReadMockHandler = (overrideResponse?: Widget | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Widget> | Widget), options?: RequestHandlerOptions) => {
  return http.get('*/widgets/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getWidgetsReadResponseMock(),
      { status: 200
      })
  }, options)
}

export const getWidgetsUpdateMockHandler = (overrideResponse?: Widget | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Widget> | Widget), options?: RequestHandlerOptions) => {
  return http.patch('*/widgets/:id', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getWidgetsUpdateResponseMock(),
      { status: 200
      })
  }, options)
}

export const getWidgetsDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/widgets/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getWidgetsAnalyzeMockHandler = (overrideResponse?: AnalyzeResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AnalyzeResult> | AnalyzeResult), options?: RequestHandlerOptions) => {
  return http.post('*/widgets/:id/analyze', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getWidgetsAnalyzeResponseMock(),
      { status: 200
      })
  }, options)
}
export const getWidgetsMock = () => [
  getWidgetsListMockHandler(),
  getWidgetsCreateMockHandler(),
  getWidgetsReadMockHandler(),
  getWidgetsUpdateMockHandler(),
  getWidgetsDeleteMockHandler(),
  getWidgetsAnalyzeMockHandler()
]
