/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import type {
  AnalyzeResult
} from '../models/analyzeResult';

import type {
  Error
} from '../models/error';

import type {
  Widget
} from '../models/widget';

import type {
  WidgetList
} from '../models/widgetList';

import type {
  WidgetMergePatchUpdate
} from '../models/widgetMergePatchUpdate';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * List widgets
 */
export type widgetsListResponse200 = {
  data: WidgetList
  status: 200
}

export type widgetsListResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type widgetsListResponseSuccess = (widgetsListResponse200) & {
  headers: Headers;
};
export type widgetsListResponseError = (widgetsListResponseDefault) & {
  headers: Headers;
};

export type widgetsListResponse = (widgetsListResponseSuccess | widgetsListResponseError)

export const getWidgetsListUrl = () => {




  return `http://localhost:4010/widgets`
}

export const widgetsList = async ( options?: RequestInit): Promise<widgetsListResponse> => {

  const res = await fetch(getWidgetsListUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsListResponse
}


/**
 * Create a widget
 */
export type widgetsCreateResponse200 = {
  data: Widget
  status: 200
}

export type widgetsCreateResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type widgetsCreateResponseSuccess = (widgetsCreateResponse200) & {
  headers: Headers;
};
export type widgetsCreateResponseError = (widgetsCreateResponseDefault) & {
  headers: Headers;
};

export type widgetsCreateResponse = (widgetsCreateResponseSuccess | widgetsCreateResponseError)

export const getWidgetsCreateUrl = () => {




  return `http://localhost:4010/widgets`
}

export const widgetsCreate = async (widget: Widget, options?: RequestInit): Promise<widgetsCreateResponse> => {

  const res = await fetch(getWidgetsCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      widget,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsCreateResponse
}


/**
 * Read widgets
 */
export type widgetsReadResponse200 = {
  data: Widget
  status: 200
}

export type widgetsReadResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type widgetsReadResponseSuccess = (widgetsReadResponse200) & {
  headers: Headers;
};
export type widgetsReadResponseError = (widgetsReadResponseDefault) & {
  headers: Headers;
};

export type widgetsReadResponse = (widgetsReadResponseSuccess | widgetsReadResponseError)

export const getWidgetsReadUrl = (id: string,) => {




  return `http://localhost:4010/widgets/${id}`
}

export const widgetsRead = async (id: string, options?: RequestInit): Promise<widgetsReadResponse> => {

  const res = await fetch(getWidgetsReadUrl(id),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsReadResponse
}


/**
 * Update a widget
 */
export type widgetsUpdateResponse200 = {
  data: Widget
  status: 200
}

export type widgetsUpdateResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type widgetsUpdateResponseSuccess = (widgetsUpdateResponse200) & {
  headers: Headers;
};
export type widgetsUpdateResponseError = (widgetsUpdateResponseDefault) & {
  headers: Headers;
};

export type widgetsUpdateResponse = (widgetsUpdateResponseSuccess | widgetsUpdateResponseError)

export const getWidgetsUpdateUrl = (id: string,) => {




  return `http://localhost:4010/widgets/${id}`
}

export const widgetsUpdate = async (id: string,
    widgetMergePatchUpdate: WidgetMergePatchUpdate, options?: RequestInit): Promise<widgetsUpdateResponse> => {

  const res = await fetch(getWidgetsUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/merge-patch+json', ...options?.headers },
    body: JSON.stringify(
      widgetMergePatchUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsUpdateResponse
}


/**
 * Delete a widget
 */
export type widgetsDeleteResponse204 = {
  data: void
  status: 204
}

export type widgetsDeleteResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 204>
}

export type widgetsDeleteResponseSuccess = (widgetsDeleteResponse204) & {
  headers: Headers;
};
export type widgetsDeleteResponseError = (widgetsDeleteResponseDefault) & {
  headers: Headers;
};

export type widgetsDeleteResponse = (widgetsDeleteResponseSuccess | widgetsDeleteResponseError)

export const getWidgetsDeleteUrl = (id: string,) => {




  return `http://localhost:4010/widgets/${id}`
}

export const widgetsDelete = async (id: string, options?: RequestInit): Promise<widgetsDeleteResponse> => {

  const res = await fetch(getWidgetsDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsDeleteResponse
}


/**
 * Analyze a widget
 */
export type widgetsAnalyzeResponse200 = {
  data: AnalyzeResult
  status: 200
}

export type widgetsAnalyzeResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type widgetsAnalyzeResponseSuccess = (widgetsAnalyzeResponse200) & {
  headers: Headers;
};
export type widgetsAnalyzeResponseError = (widgetsAnalyzeResponseDefault) & {
  headers: Headers;
};

export type widgetsAnalyzeResponse = (widgetsAnalyzeResponseSuccess | widgetsAnalyzeResponseError)

export const getWidgetsAnalyzeUrl = (id: string,) => {




  return `http://localhost:4010/widgets/${id}/analyze`
}

export const widgetsAnalyze = async (id: string, options?: RequestInit): Promise<widgetsAnalyzeResponse> => {

  const res = await fetch(getWidgetsAnalyzeUrl(id),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetsAnalyzeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as widgetsAnalyzeResponse
}


