/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import type { WidgetColor } from './widgetColor';

export interface Widget {
  id: string;
  weight: number;
  color: WidgetColor;
}
