/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import type { WidgetMergePatchUpdateColor } from './widgetMergePatchUpdateColor';

export interface WidgetMergePatchUpdate {
  id?: string;
  weight?: number;
  color?: WidgetMergePatchUpdateColor;
}
