/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import type { Widget } from './widget';

export interface WidgetList {
  items: Widget[];
}
