/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */

export type WidgetColor = typeof WidgetColor[keyof typeof WidgetColor];


export const WidgetColor = {
  red: 'red',
  blue: 'blue',
} as const;
