/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */

export type WidgetMergePatchUpdateColor = typeof WidgetMergePatchUpdateColor[keyof typeof WidgetMergePatchUpdateColor];


export const WidgetMergePatchUpdateColor = {
  red: 'red',
  blue: 'blue',
} as const;
